### ISSUE TITLE
Start work on the UHF Transceiver Subsystem

### ISSUE THREAD

**Issue by RadhePatel04** [AlbertaSat/BIRDS-X_PCB#1]
## Description:
Start work on UHF transceiver subsystem (essentially exposes port that ground station talks to for now - eventually replicate actual UHF transceiver functionality) 

## Deliverables
- [ ]  ToDo

## Resources

- ToDO

**Comment by DeflateAwning** [comment]
Hmm is this the right repo?

**Comment by DeflateAwning** [comment]
Closed as this is the wrong repo
